### ISSUE TITLE
Strange Exception

### ISSUE THREAD

**Issue by fosskers** [rgleichman/glance#2]
Hi there, `glance` throws the following:

```
glance-exe: evalPattern: No pattern in case for PBangPat (PVar (Ident "n"))
CallStack (from HasCallStack):
  error, called at app/Translate.hs:249:8 in main:Translate
```
on [this code here](https://github.com/fosskers/axe/blob/master/Axe.hs)

**Comment by rgleichman** [comment]
Thank you for trying out Glance. At the moment, Glance translates only a subset of Haskell syntax, so this error is completely expected. Bang patterns are currently not-supported, so it is probably failing at [line 52 of your code](https://github.com/fosskers/axe/blob/master/Axe.hs#L52). Try changing
```work c !n s = do```
to
```work c n s = do```
and then re-running Glance.

For reference, the `PBandPat` is a constructor for `Pat`, which is part of haskell-src-exts ([see here](http://hackage.haskell.org/package/haskell-src-exts-1.19.0/docs/Language-Haskell-Exts-Syntax.html#t:Pat))

**Comment by fosskers** [comment]
Yup, works if I remove the bang. Thanks!
